"""create invoice templates table

Revision ID: f61f98677532
Revises:
Create Date: 2026-05-07 20:09:56.325037

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f61f98677532"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoice_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("preview_image", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invoice_templates_id"), "invoice_templates", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_invoice_templates_is_active"),
        "invoice_templates",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoice_templates_key"), "invoice_templates", ["key"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invoice_templates_key"), table_name="invoice_templates")
    op.drop_index(
        op.f("ix_invoice_templates_is_active"), table_name="invoice_templates"
    )
    op.drop_index(op.f("ix_invoice_templates_id"), table_name="invoice_templates")
    op.drop_table("invoice_templates")
    # ### end Alembic commands ###
