SAMPLE_PREVIEW_CONTEXT = {
    "company": {
        "name": "SmartBiz Solutions",
        "logo_url": None,
        "address": "123 Business Street\nNew York, NY 10001",
        "address_lines": ["123 Business Street", "New York, NY 10001"],
        "email": "billing@smartbiz.com",
        "phone": "+1 555 123 4567",
        "website": "smartbiz.com",
        "tax_id": "EIN 12-3456789",
        "tax_number": "EIN 12-3456789",
        "registration_number": None,
    },
    "client": {
        "name": "John Smith",
        "address": "45 Client Avenue\nLos Angeles, CA 90001",
        "address_lines": ["45 Client Avenue", "Los Angeles, CA 90001"],
        "email": "john@example.com",
        "phone": "+1 555 987 6543",
        "tax_id": None,
    },
    "invoice": {
        "number": "INV-1001",
        "issue_date": "May 1, 2026",
        "due_date": "May 10, 2026",
        "currency": "$",
        "po_number": None,
        "status": "DRAFT",
        "notes": "Thank you for your business.",
        "terms": None,
        "payment_details": None,
    },
    "items": [
        {
            "description": "Website Design",
            "details": "Landing page and responsive design",
            "quantity": 1,
            "unit": None,
            "unit_price": 500.00,
            "amount": 500.00,
        },
        {
            "description": "Hosting",
            "details": "Monthly hosting plan",
            "quantity": 2,
            "unit": None,
            "unit_price": 50.00,
            "amount": 100.00,
        },
    ],
    "totals": {
        "subtotal": 600.00,
        "discount": 0.00,
        "discount_label": "Discount",
        "tax": 60.00,
        "tax_label": "Tax",
        "shipping": 0.00,
        "total": 660.00,
        "amount_paid": 0.00,
        "balance_due": 660.00,
    },
}
